version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: mvi
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: autodb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/autodb
      SPRING_DATASOURCE_USERNAME: mvi
      SPRING_DATASOURCE_PASSWORD: 123

volumes:
  postgres-data: